"use client";

import Head from "next/head";
import { useRef, useState } from "react";

export default function Home() {
	const inputRef = useRef<HTMLInputElement>(null);
	const [shortURL, setShortURL] = useState("");

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault();

		const url = inputRef.current?.value;

		fetch("/api/shortUrl", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({ url }),
		})
			.then((res) => res.json())
			.then((data) => {
				console.log({ data });
				setShortURL(data.shortUrl);
			})
			.catch((err) => {
				console.log({ err });
			});
	};
	return (
		<div className="min-vh-100 py-0 px-[0.5rem] flex flex-col items-center justify-center h-screen">
			<Head>
				<title>URL Shortener</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="py-[5rem] px-0 flex flex-col justify-center items-center">
				<h1 className="m-0 text-[4rem] text-center">URL Shortener</h1>

				<p className="text-center text-2xl">Acorta tus URLs aquí</p>

				<div className="flex items-center justify-center flex-col sm:flex-row flex-wrap max-w-[800px] mt-12">
					<form
						className="m-4 p-6 text-left text-inherit border border-slate-[#eaeaea] border-solid rounded-[10px] transition-colors duration-150 ease-in-out border-transition-colors hover:text-blue-600 focus:text-blue-600 active:text-blue-600 hover:border-blue-600 focus:border-blue-600 active:border-blue-600"
						onSubmit={handleSubmit}
					>
						<input
							ref={inputRef}
							type="text"
							className="m-0.5 text-xl p-4"
							placeholder="URL"
						/>
						<button className="m-0.5 text-xl p-4">Acorta</button>
						<span className="m-0.5 text-xl p-4 text-inherit">{shortURL}</span>
					</form>
				</div>
			</main>
		</div>
	);
}
